[project]
name = "semantic-query-tests"
version = "0.1.0"
description = "Test suite for Semantic Query API extension"
requires-python = ">=3.8"
dependencies = [
    "duckdb>=0.9.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
